# Generated by Django 4.1.1 on 2022-09-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuxProvocacaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peticao', models.IntegerField()),
                ('chave', models.IntegerField()),
                ('tipo_chave', models.CharField(choices=[('P', 'Provocação'), ('R', 'Resposta')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Capitania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CargoTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'cargo título',
                'verbose_name_plural': 'cargos título',
            },
        ),
        migrations.CreateModel(
            name='Comarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Conselheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_parecer_regio', models.DateField(blank=True, null=True)),
                ('referencia_documental', models.CharField(max_length=500)),
                ('sumula', models.TextField()),
                ('data_consulta', models.DateField(blank=True, null=True)),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
                ('resumo', models.TextField()),
                ('parecer_regio', models.TextField()),
                ('registro', models.CharField(choices=[('PART', 'Partes'), ('CAPIT', 'Capitanias'), ('AVUL', 'Avulso'), ('MINASGER', 'Minas Gerais'), ('CAPIT', 'Capitania'), ('SERVREAL', 'Serviço Real'), ('IND', 'Indireta'), ('OUTRASCAPS', 'Outras Capitanias')], max_length=100)),
                ('conselheiros', models.ManyToManyField(blank=True, related_name='consultas', to='historia.conselheiro')),
            ],
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cargo_titulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historia.cargotitulo')),
            ],
            options={
                'verbose_name': 'destinatário',
                'verbose_name_plural': 'destinatários',
            },
        ),
        migrations.CreateModel(
            name='Freguesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Mandado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
                ('registro', models.CharField(choices=[('PART', 'Partes'), ('CAPIT', 'Capitanias'), ('AVUL', 'Avulso'), ('MINASGER', 'Minas Gerais'), ('CAPIT', 'Capitania'), ('SERVREAL', 'Serviço Real'), ('IND', 'Indireta'), ('OUTRASCAPS', 'Outras Capitanias')], max_length=100)),
                ('referencia', models.CharField(max_length=500)),
                ('resumo', models.TextField()),
                ('mandado', models.CharField(max_length=80)),
                ('nome_quem_envia', models.CharField(choices=[('Secretário', 'Secretário'), ('Conselho', 'Conselho')], max_length=80)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historia.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Migracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_a', models.DateTimeField(auto_now_add=True)),
                ('ficheiro_provocacao', models.FileField(upload_to='historia/dados_upload/')),
                ('ficheiro_consulta', models.FileField(upload_to='historia/dados_upload/')),
                ('ficheiro_resposta', models.FileField(upload_to='historia/dados_upload/')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaCitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'pessoa citada',
                'verbose_name_plural': 'pessoas citadas',
            },
        ),
        migrations.CreateModel(
            name='Requerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcador_social', models.CharField(max_length=20)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('D', 'Desconhecido')], max_length=1, null=True)),
                ('nome', models.CharField(max_length=80)),
                ('cargo_titulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='historia.cargotitulo')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('ano', models.CharField(max_length=4)),
                ('resumo', models.TextField()),
                ('referencia', models.CharField(max_length=500)),
                ('nova_ordem_n_comprimento', models.CharField(max_length=50)),
                ('tipologia', models.CharField(choices=[('ordem', 'Ordem'), ('Ordem de informe (com declaração de procedimento)', 'Ordem de informe'), ('Provisão', 'Provisão'), ('Alvará', 'Alvará'), ('Carta de recomendação', 'Carta de recomendação'), ('Ordem de informe (com declaração de procedimento)', 'Ordem de informe (com declaração de procedimento)'), ('Alvará de Lei', 'Alvará de Lei'), ('Lei', 'Lei'), ('Mandato', 'Mandato'), ('Escusada', 'Escusada'), ('Sem informação', 'Sem informação'), ('ordem', 'ordem')], max_length=60)),
                ('registro', models.CharField(choices=[('PART', 'Partes'), ('CAPIT', 'Capitanias'), ('AVUL', 'Avulso'), ('MINASGER', 'Minas Gerais'), ('CAPIT', 'Capitania'), ('SERVREAL', 'Serviço Real'), ('IND', 'Indireta'), ('OUTRASCAPS', 'Outras Capitanias')], max_length=100)),
                ('destinatarios', models.ManyToManyField(blank=True, related_name='respostas', to='historia.destinatario')),
                ('requerentes', models.ManyToManyField(blank=True, related_name='respostas', to='historia.requerente')),
            ],
        ),
        migrations.CreateModel(
            name='SecretarioConselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('quem_responde', models.CharField(choices=[('SECR', 'Secretário'), ('CONC', 'Conselho')], max_length=10)),
            ],
            options={
                'verbose_name': 'secretário de concelho',
                'verbose_name_plural': 'secretários de concelho',
            },
        ),
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtema_texto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_texto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TemaSubtema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia.subtema')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia.tema')),
            ],
            options={
                'verbose_name': 'tema e subtema',
                'verbose_name_plural': 'temas e subtemas',
            },
        ),
        migrations.CreateModel(
            name='Ultramar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField()),
                ('registro', models.CharField(choices=[('PART', 'Partes'), ('CAPIT', 'Capitanias'), ('AVUL', 'Avulso'), ('MINASGER', 'Minas Gerais'), ('CAPIT', 'Capitania'), ('SERVREAL', 'Serviço Real'), ('IND', 'Indireta'), ('OUTRASCAPS', 'Outras Capitanias')], max_length=100)),
                ('data', models.DateField()),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
                ('referencia', models.CharField(max_length=500)),
                ('autoridade', models.CharField(blank=True, max_length=80, null=True)),
                ('consulta', models.ManyToManyField(blank=True, related_name='ultramares', to='historia.consulta')),
                ('respostas', models.ManyToManyField(blank=True, related_name='ultramares', to='historia.resposta')),
                ('tema_subtemas', models.ManyToManyField(blank=True, related_name='ultramares', to='historia.temasubtema')),
            ],
            options={
                'verbose_name': 'ultramar',
                'verbose_name_plural': 'ultramares',
            },
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('capitania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='historia.capitania')),
                ('comarcas', models.ManyToManyField(blank=True, related_name='termos', to='historia.comarca')),
                ('freguesias', models.ManyToManyField(blank=True, related_name='termos', to='historia.freguesia')),
            ],
        ),
        migrations.AddField(
            model_name='subtema',
            name='tema',
            field=models.ManyToManyField(blank=True, related_name='subtemas', through='historia.TemaSubtema', to='historia.tema'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='secretario_concelho',
            field=models.ManyToManyField(blank=True, related_name='respostas', to='historia.secretarioconselho'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='tema_subtemas',
            field=models.ManyToManyField(blank=True, related_name='respostas', to='historia.temasubtema'),
        ),
        migrations.CreateModel(
            name='Provocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField()),
                ('referencia', models.CharField(max_length=500)),
                ('data', models.DateField(blank=True, null=True)),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
                ('registro', models.CharField(max_length=100)),
                ('remetente', models.CharField(max_length=150)),
                ('destinatario_autoridade', models.CharField(max_length=40)),
                ('cargo_titulo_remetente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='historia.cargotitulo')),
                ('consultas', models.ManyToManyField(blank=True, related_name='provocacoes', to='historia.consulta')),
                ('mandado', models.ManyToManyField(blank=True, related_name='provocacoes', to='historia.mandado')),
                ('pessoas_citadas', models.ManyToManyField(blank=True, related_name='provocacoes', to='historia.pessoacitada')),
                ('requerentes', models.ManyToManyField(blank=True, related_name='provocacoes', to='historia.requerente')),
                ('respostas', models.ManyToManyField(blank=True, related_name='provocacoes', to='historia.resposta')),
                ('tema_subtemas', models.ManyToManyField(blank=True, related_name='provocacoes', to='historia.temasubtema')),
                ('termos', models.ManyToManyField(blank=True, related_name='provocacoes', to='historia.termo')),
                ('ultramar', models.ManyToManyField(blank=True, related_name='provocacoes', to='historia.ultramar')),
            ],
            options={
                'verbose_name': 'provocação',
                'verbose_name_plural': 'provocações',
            },
        ),
        migrations.AddField(
            model_name='mandado',
            name='pessoas_citadas',
            field=models.ManyToManyField(blank=True, related_name='mandados', to='historia.pessoacitada'),
        ),
        migrations.AddField(
            model_name='mandado',
            name='requerentes',
            field=models.ManyToManyField(blank=True, related_name='mandados', to='historia.requerente'),
        ),
        migrations.AddField(
            model_name='mandado',
            name='respostas',
            field=models.ManyToManyField(blank=True, related_name='mandados', to='historia.resposta'),
        ),
        migrations.AddField(
            model_name='mandado',
            name='tema_subtemas',
            field=models.ManyToManyField(blank=True, related_name='mandados', to='historia.temasubtema'),
        ),
        migrations.AddField(
            model_name='mandado',
            name='ultramar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historia.ultramar'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='pessoas_citadas',
            field=models.ManyToManyField(blank=True, related_name='consultas', to='historia.pessoacitada'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='requerentes',
            field=models.ManyToManyField(blank=True, related_name='consultas', to='historia.requerente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='respostas',
            field=models.ManyToManyField(blank=True, related_name='consultas', to='historia.resposta'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tema_subtemas',
            field=models.ManyToManyField(blank=True, related_name='consultas', to='historia.temasubtema'),
        ),
    ]
