# Generated by Django 4.1.1 on 2022-09-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='parecer_regio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='sumula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mandado',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mandado',
            name='mandado',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='mandado',
            name='nome_quem_envia',
            field=models.CharField(blank=True, choices=[('Secretário', 'Secretário'), ('Conselho', 'Conselho')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='mandado',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provocacao',
            name='destinatario_autoridade',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='provocacao',
            name='registro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provocacao',
            name='remetente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='provocacao',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requerente',
            name='nome',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='ano',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='nova_ordem_n_comprimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='referencia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='registro',
            field=models.CharField(blank=True, choices=[('PART', 'Partes'), ('CAPIT', 'Capitanias'), ('AVUL', 'Avulso'), ('MINASGER', 'Minas Gerais'), ('CAPIT', 'Capitania'), ('SERVREAL', 'Serviço Real'), ('IND', 'Indireta'), ('OUTRASCAPS', 'Outras Capitanias')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('ordem', 'Ordem'), ('Ordem de informe (com declaração de procedimento)', 'Ordem de informe'), ('Provisão', 'Provisão'), ('Alvará', 'Alvará'), ('Carta de recomendação', 'Carta de recomendação'), ('Ordem de informe (com declaração de procedimento)', 'Ordem de informe (com declaração de procedimento)'), ('Alvará de Lei', 'Alvará de Lei'), ('Lei', 'Lei'), ('Mandato', 'Mandato'), ('Escusada', 'Escusada'), ('Sem informação', 'Sem informação'), ('ordem', 'ordem')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ultramar',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultramar',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
