# Generated by Django 4.1.1 on 2022-09-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='registro',
            field=models.CharField(choices=[('PART', 'Partes'), ('CAPIT', 'Capitanias'), ('AVUL', 'Avulso'), ('MINASGER', 'Minas Gerais'), ('CAPIT', 'Capitania'), ('SERVREAL', 'Serviço Real'), ('IND', 'Indireta'), ('OUTRASCAPS', 'Outras Capitanias')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mandado',
            name='registro',
            field=models.CharField(choices=[('PART', 'Partes'), ('CAPIT', 'Capitanias'), ('AVUL', 'Avulso'), ('MINASGER', 'Minas Gerais'), ('CAPIT', 'Capitania'), ('SERVREAL', 'Serviço Real'), ('IND', 'Indireta'), ('OUTRASCAPS', 'Outras Capitanias')], max_length=100),
        ),
        migrations.AlterField(
            model_name='provocacao',
            name='registro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='registro',
            field=models.CharField(choices=[('PART', 'Partes'), ('CAPIT', 'Capitanias'), ('AVUL', 'Avulso'), ('MINASGER', 'Minas Gerais'), ('CAPIT', 'Capitania'), ('SERVREAL', 'Serviço Real'), ('IND', 'Indireta'), ('OUTRASCAPS', 'Outras Capitanias')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ultramar',
            name='registro',
            field=models.CharField(choices=[('PART', 'Partes'), ('CAPIT', 'Capitanias'), ('AVUL', 'Avulso'), ('MINASGER', 'Minas Gerais'), ('CAPIT', 'Capitania'), ('SERVREAL', 'Serviço Real'), ('IND', 'Indireta'), ('OUTRASCAPS', 'Outras Capitanias')], max_length=100),
        ),
    ]
