# Generated by Django 4.1.1 on 2022-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='registro',
            field=models.CharField(choices=[('Minas Gerais', 'Minas Gerais'), ('Partes', 'Partes'), ('Capitanias', 'Capitanias'), ('Avulso', 'Avulso'), ('Minas Gerais', 'Minas Gerais'), ('Capitania', 'Capitania'), ('Serviço Real', 'Serviço Real'), ('Indireta', 'Indireta'), ('Serviço Real', 'Serviço Real'), ('Outras Capitanias', 'Outras Capitanias')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('Indireta', 'Indireta'), ('Provisões', 'Provisões'), ('Ofícios', 'Ofício'), ('Capitania', 'Capitania'), ('ordem', 'Ordem'), ('Ordem de informe (com declaração de procedimento)', 'Ordem de informe'), ('Provisão', 'Provisão'), ('Alvará', 'Alvará'), ('Carta de recomendação', 'Carta de recomendação'), ('Ordem de informe (com declaração de procedimento)', 'Ordem de informe (com declaração de procedimento)'), ('Alvará de Lei', 'Alvará de Lei'), ('Lei', 'Lei'), ('Mandato', 'Mandato'), ('Escusada', 'Escusada'), ('Sem informação', 'Sem informação'), ('ordem', 'ordem')], max_length=60, null=True),
        ),
    ]
