# Generated by Django 4.1.1 on 2022-09-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0002_alter_consulta_parecer_regio_alter_consulta_resumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultramar',
            name='teste',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
