# Generated by Django 4.1.1 on 2022-09-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0002_alter_consulta_registro_alter_mandado_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='referencia_documental',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mandado',
            name='referencia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='provocacao',
            name='referencia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='referencia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ultramar',
            name='referencia',
            field=models.CharField(max_length=500),
        ),
    ]
