# Generated by Django 4.1.1 on 2022-09-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0003_ultramar_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultramar',
            name='teste',
        ),
    ]
